name: unit tests

on:
  push:
    branches: [ "develop","master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  CI:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install black mypy isort

    # ---- Code Quality Checks ----

    - name: Sort imports with isort
      run: |
        # Automatically sort and group Python imports
        isort .

    - name: Format code with black
      run: |
        # Ensure code style consistency (PEP8 + black rules)
        black --check --verbose .

    - name: Type check with mypy
      run: |
        # Static type checking with strict mode to catch typing issues
        mypy --strict .

    # ---- Tests ----

#    - name: Run unit tests
#      run: |
#        # Discover and run all unit tests under the "tests" directory
#        python -m unittest discover -s tests -p "*.py"